# Generated by Django 5.0.1 on 2024-01-23 23:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('exercise_type', models.CharField(max_length=150)),
                ('muscle', models.CharField(max_length=150)),
                ('equipment', models.CharField(max_length=150)),
                ('difficulty', models.CharField(max_length=150)),
                ('instructions', models.TextField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='customuser',
            options={},
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('set_number', models.IntegerField()),
                ('reps', models.IntegerField(blank=True, null=True)),
                ('volume', models.IntegerField(blank=True, null=True)),
                ('rating', models.IntegerField()),
                ('datetime', models.DateTimeField()),
                ('unit', models.CharField(choices=[('lbs', 'lbs'), ('kg', 'kg'), ('sec', 'sec'), ('min', 'min'), ('pounds', 'pounds'), ('kilograms', 'kilograms'), ('seconds', 'seconds'), ('minutes', 'minutes'), ('hours', 'hours'), ('hrs', 'hrs')], max_length=150)),
                ('externalExcercise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.externalexercise')),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.workout')),
            ],
        ),
    ]
