# Generated by Django 5.0.1 on 2024-02-01 03:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="exercise",
            name="externalExcercise",
        ),
        migrations.AddField(
            model_name="exercise",
            name="external_exercise",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="api.externalexercise",
            ),
        ),
        migrations.AlterField(
            model_name="exercise",
            name="datetime",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
