# Generated by Django 5.0.1 on 2024-02-02 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_exercise_externalexcercise_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalexercise',
            name='name',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
