# Generated by Django 5.0.1 on 2024-02-02 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_externalexercise_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='externalexercise',
            old_name='exercise_type',
            new_name='type',
        ),
    ]
