# Generated by Django 4.2.1 on 2024-02-13 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_remove_exercise_rating_remove_exercise_reps_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="externalexercise",
            name="favorite",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="exercise",
            name="sets",
            field=models.JSONField(default=dict),
        ),
    ]
