# Generated by Django 5.0.1 on 2024-02-02 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_exercise_type_externalexercise_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalexercise',
            name='instructions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
