# Generated by Django 4.2.1 on 2024-03-05 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_workoutplan"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="pref_unit",
            field=models.CharField(
                choices=[("lbs", "lbs"), ("kg", "kg")], default="lbs", max_length=150
            ),
        ),
        migrations.AlterField(
            model_name="exercise",
            name="unit",
            field=models.CharField(
                choices=[("lbs", "lbs"), ("kg", "kg"), ("timed", "timed")],
                max_length=150,
            ),
        ),
    ]
