# Generated by Django 5.0.1 on 2024-02-02 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_externalexercise_instructions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalexercise',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterUniqueTogether(
            name='externalexercise',
            unique_together={('name', 'muscle')},
        ),
    ]
