# Generated by Django 4.2.1 on 2024-02-02 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_externalexercise_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='datetime',
        ),
    ]
